version: build-{build}.{branch}
platform: x64

clone_folder: c:\gopath\src\gopkg.in\src-d\go-kallax.v1
shallow_clone: true

environment:
  GOPATH: c:\gopath
  PGPASSWORD: "Password12!"
  PGUSER: "postgres"
  DBUSER: "postgres"
  DBPASS: "Password12!"

services:
  - postgresql96

install:
  - set PATH=C:\Program Files\PostgreSQL\9.6\bin\;%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go get -v -t .\...

build: off

test_script:
  - createdb testing
  - go test -v .\...
